insert into public.territories (id, name, coordinates)
values
  ('Setor 4', 'Territorio das Alturas (Setor 4)', '19.4324 S, 69.2154 W'),
  ('Setor 7G', 'Selvageria Urbana (Setor 7G)', '23.5505 S, 46.6333 W'),
  ('Setor 2A', 'Margens do Igapo (Setor 2A)', '3.0722 S, 60.0125 W'),
  ('Setor 9N', 'Aluvioes do Vale Central (Setor 9N)', '33.4489 S, 70.6693 W')
on conflict (id) do update
set name = excluded.name,
    coordinates = excluded.coordinates;

insert into public.fragments (
  id,
  title,
  type,
  source,
  territory_id,
  content,
  map_position_x,
  map_position_y,
  image_url,
  media_links,
  is_open_to_connections,
  connected_fragment_ids,
  author_id,
  created_at
)
values
  (
    'alti-1',
    'Sussurros do Altiplano',
    'audio',
    'Terras Altas Andinas',
    'Setor 4',
    'Gravacao binaural das correntes de ar frio que sopram atraves das frestas rochosas rituais no desfiladeiro alto de Tarapaca.',
    30,
    25,
    null,
    array[]::text[],
    true,
    array['poet-2', 'memb-3']::text[],
    null,
    '2026-05-12T14:35:00Z'
  ),
  (
    'poet-2',
    '"A terra nao lembra nossos nomes, apenas o ritmo de nossos passos e o calor das sementes que deixamos para tras."',
    'poetic',
    'Tradicao Oral #22',
    'Setor 4',
    'Fragmento lirico coletado durante os rituais de semeadura noturna.',
    74,
    35,
    null,
    array[]::text[],
    true,
    array['alti-1']::text[],
    null,
    '2026-05-18T09:12:00Z'
  ),
  (
    'memb-3',
    'Membrana Viva',
    'visual',
    'Arquivo Botanico',
    'Setor 4',
    'Registro fotografico de uma simbiose de musgos andinos cultivados sobre hardware de comunicacao abandonado.',
    50,
    64,
    'https://images.unsplash.com/photo-1545231027-63b39f612acf?q=80&w=600&auto=format&fit=crop',
    array['https://images.unsplash.com/photo-1545231027-63b39f612acf?q=80&w=600&auto=format&fit=crop'],
    true,
    array['alti-1']::text[],
    null,
    '2026-05-24T18:40:00Z'
  ),
  (
    'mang-4',
    'Eco Resonante do Igapo',
    'audio',
    'Guardas da Mare',
    'Setor 2A',
    'Ruidos estalados produzidos por colonias de caranguejos de mangue sob as raizes suspensas durante o pico da mare vazante.',
    18,
    72,
    null,
    array[]::text[],
    true,
    array[]::text[],
    null,
    '2026-05-27T11:20:00Z'
  ),
  (
    'flor-5',
    'Xilo-Sinalizadores de Solo',
    'visual',
    'Laboratorio das Raizes',
    'Setor 7G',
    'Raizes aereas impregnadas com biocatalisadores biolinescentes naturais que reagem aos micro-tremores de terra.',
    82,
    75,
    'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=600&auto=format&fit=crop',
    array['https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=600&auto=format&fit=crop'],
    true,
    array['linc-7']::text[],
    null,
    '2026-05-29T10:00:00Z'
  ),
  (
    'vale-6',
    'Canto das Aguas Subterraneas',
    'poetic',
    'Poetica do Meio Bio',
    'Setor 9N',
    'Expressao falada transmitida por tubos hidricos em fossos subterraneos desativados.',
    46,
    42,
    null,
    array[]::text[],
    true,
    array[]::text[],
    null,
    '2026-06-01T12:00:00Z'
  ),
  (
    'linc-7',
    'Comunidade Liquenica Ativa',
    'visual',
    'Fotografia de Contato',
    'Setor 7G',
    'Comunidades simbioticas circulares formadas na interface entre cascas de arvores deciduas e placas metalicas fotovoltaicas intemperizadas.',
    88,
    55,
    'https://images.unsplash.com/photo-1502082553048-f009c37129b9?q=80&w=600&auto=format&fit=crop',
    array['https://images.unsplash.com/photo-1502082553048-f009c37129b9?q=80&w=600&auto=format&fit=crop'],
    true,
    array['flor-5']::text[],
    null,
    '2026-06-02T15:30:00Z'
  ),
  (
    'vento-8',
    'Murmurios do Vento Solar',
    'audio',
    'Coletor Atmosferico',
    'Setor 4',
    'Registro acustico sintetizado a partir de alteracoes geomagneticas fracas causadas por ventos solares na atmosfera de baixa pressao do Altiplano.',
    14,
    40,
    null,
    array[]::text[],
    true,
    array[]::text[],
    null,
    '2026-06-02T19:45:00Z'
  )
on conflict (id) do update
set title = excluded.title,
    type = excluded.type,
    source = excluded.source,
    territory_id = excluded.territory_id,
    content = excluded.content,
    map_position_x = excluded.map_position_x,
    map_position_y = excluded.map_position_y,
    image_url = excluded.image_url,
    media_links = excluded.media_links,
    is_open_to_connections = excluded.is_open_to_connections,
    connected_fragment_ids = excluded.connected_fragment_ids,
    created_at = excluded.created_at;
